# Generated by Django 4.0.7 on 2022-09-07 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveuniverse", "0007_evetype_description"),
        ("freight", "0003_check_eveuniverse_fully_loaded"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contracthandler",
            name="organization",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="eveuniverse.eveentity",
            ),
        ),
        migrations.DeleteModel(
            name="EveEntity",
        ),
    ]
